### ISSUE TITLE
Is it a good idea to export the Properties ExportComputer and ExportUser?

### ISSUE THREAD

**Issue by schittli** [jdhitsolutions/PSJsonCredential#3]
Good evening Jeff
Thank you **very much** for all your great work!, it's very inspiring and useful.

You don't have to answer this issue (question) - it's OK if you just close it.

I've read the docs about your PSJsonCredential and 
#### I think it's a bad idea to export the Properties ExportComputer and ExportUser into the JSON File: 
- If a hacker gets a Credentials JSON File **with** the assigned Computer and Username, then he can directly start attacking the addressed target to decode the password.
- If a hacker gets a Credentials JSON File **without** the assigned Computer and User, then he will have to start searching the right machine to decode the password.

#### I think there is a real difference: 
Today, it's easiliy possible that a Hacker gets access to a JSON Password File without having access to the target computer itself, e.g. if a User synchronizes the JSON File (by accident, of course…) for example to Dropbox and a Hacker gets access to it - or even worse: the User shares it to his friends.

#### It's similar to the situation when I lose my house keys: 
Most citizens recognize that it's a key to open a main door - but if there is no address attached, it's hard to find the right house.

Until then, I can detect the loss and exchange the keys :-)

Kind regards, all the best,
Thomas

**Comment by jdhitsolutions** [comment]
You are very correct. In fact storing any credential to disk is a potential security risk. Creating the file, which this module can do, is merely the first step. It is still up to the user to properly secure and protect the file - for the very reasons you mention.

**Comment by jdhitsolutions** [comment]
I have pushed out v2.0.0 of the module. The metadata is now an optional feature and the command no longer rely on the CryptoAPI which means you can use the module in PowerShell Core. The commands now rely on a user defined key of length 16, 24 or 32.
